### PR TITLE
Adding ceil algorithm

### PR DESCRIPTION
**Pull request by RicardoRibeiroRodrigues**
This PR introduces the ceil algorithm, a simple algorithm to round up a float to a integer. It also uses the mojo docs syntax, this way, the tests can be run with `mojo test`.

@SatinWukerORIG Let me know if you like the doc test pattern or if would be better to create dedicated test files.

### CODE REVIEW

**Comment by SatinWukerORIG** [comment]
Sorry for the late reply. I was looking at the doc test documentation, but was unable to run the test. What version are you using, and can you tell me more specifically about it? Thank you!
@RicardoRibeiroRodrigues

**Comment by RicardoRibeiroRodrigues** [comment]
Hello,

I noticed that the project has recently released a major update, moving from the modular CLI to the new magic CLI in version 24.4.0. I've downloaded the latest version and will be submitting a PR to include the necessary project files to run .mojo files with the updated system.

From what I understand, the new syntax for running our current algorithm tests is now `magic run mojo test maths`.

Update: Please see PR #10 for the magic files.

**Comment by RicardoRibeiroRodrigues** [comment]
Hi @SatinWukerORIG,

With the latest version of Magic, tests are now running successfully using the command `magic run mojo test maths`. Would you like us to proceed with this format for future testing?

Additionally, could I get a review on the PRs when you have a chance?

Thanks!

**Review by SatinWukerORIG — APPROVED** [review]
This is a good test format. Sorry for the late review, but next time you can try "request review", and I will come to review your code! Sometimes I receive too much emails, so I would possibly forget or ignore some, sorry!

**Comment by RicardoRibeiroRodrigues** [comment]
@SatinWukerORIG for some reason in this repo I cannot request review, I added a PR (https://github.com/TheAlgorithms/Mojo/pull/11) to add a automation of review request for Mojo

**Pull request merged**
